wandb_version: 1

learning_rate:
  desc: null
  value: 0.02
architecture:
  desc: null
  value: EfficientNet-RCNN
dataset:
  desc: null
  value: OpenForensics
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1703042932.140653
    t:
      1:
      - 1
      - 41
      - 55
      - 105
      2:
      - 1
      - 41
      - 55
      - 105
      3:
      - 2
      - 16
      - 23
      4: 3.10.11
      5: 0.16.1
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
