seed: 1
device: cuda

data:
  root: data/deepfake_dataset
  test_split: test
  num_classes: 2
  img_size: 224

defaults:
  model:
    kind: timm
    pretrained: false
  inference:
    batch_size: 64
    num_workers: 4
  transforms:
    eval:
      resize: true
      center_crop: true

models:
  repvit_m1:
    model:
      id: repvit_m1.dist_in1k
    inference:
      weights: weights/repvit_m1.pth

  efficientformerv2_s1:
    model:
      id: efficientformerv2_s1
    inference:
      weights: weights/efficientformerv2_s1.pth
  faster_vit_2_224:
    model:
      id: faster_vit_2_224
    inference:
      weights: weights/faster_vit_2_224.pth

  efficientnet_b3:
    model:
      id: efficientnet_b3
    inference:
      weights: weights/efficientnet_b3.pth

selection:
  - repvit_m1
  - efficientformerv2_s1
  - faster_vit_2_224
  - efficientnet_b3
