seed: 1
device: cuda

data:
  root: data/mini_deepfake_dataset
  test_split: test
  val_split: val
  num_classes: 2
  img_size: 224

models:
  efficientnet_b3:
    output_dir: runs/efficientnet_b3
    transforms:
      eval:
        ensure_rgb: true
        val_resize: true
        val_center_crop: true
    inference:
      weights: weights/EfficientNet_10_21_2025.pth
      split: test
      batch_size: 256
      num_workers: 2
      img_size: 224
  efficientformerv2_s1:
    output_dir: runs/efficientformerv2_s1
    transforms:
      eval:
        ensure_rgb: true
        val_resize: true
        val_center_crop: true
    inference:
      weights: weights/EfficientFormerV2_S1.pth
      split: test
      batch_size: 256
      num_workers: 4
      img_size: 224
  faster_vit_2_224:
    output_dir: runs/faster_vit_2_224
    transforms:
      eval:
        ensure_rgb: true
        val_resize: true
        val_center_crop: true
    inference:
      weights: weights/FasterViT_10_20_2025.pth
      split: test
      batch_size: 256
      num_workers: 4
      img_size: 224

selection:
  - efficientnet_b3
  - efficientformerv2_s1
  - faster_vit_2_224
