seed: 1
device: cuda

data:
  root: data/mini_deepfake_dataset
  train_split: train
  val_split: val
  num_classes: 2
  img_size: 224

models:
  efficientnet_b3:
    output_dir: runs/efficientnet_b3
    transforms:
      train:
        ensure_rgb: true
        train_random_resized_crop: true
        train_random_horizontal_flip: true
        train_random_rotation: true
        train_color_jitter: true
        train_random_erasing: true
      eval:
        ensure_rgb: true
        val_resize: true
        val_center_crop: true
    training:
      epochs: 5
      batch_size: 64
      num_workers: 4
      resume: auto
  efficientformerv2_s1:
    output_dir: runs/efficientformerv2_s1
    transforms:
      train:
        ensure_rgb: true
        train_random_resized_crop: true
        train_random_horizontal_flip: true
        train_color_jitter: true
      eval:
        ensure_rgb: true
        val_resize: true
        val_center_crop: true
    training:
      epochs: 5
      batch_size: 128
      num_workers: 8
      resume: auto
  faster_vit_2_224:
    output_dir: runs/faster_vit_2_224
    transforms:
      train:
        ensure_rgb: true
        train_random_resized_crop: true
        train_random_horizontal_flip: true
        train_color_jitter: true
      eval:
        ensure_rgb: true
        val_resize: true
        val_center_crop: true
    training:
      epochs: 5
      batch_size: 64
      num_workers: 8
      resume: auto
  repvit_m1:
    output_dir: runs/repvit_m1
    transforms:
      train:
        ensure_rgb: true
        train_random_resized_crop: true
        train_random_horizontal_flip: true
        train_color_jitter: true
        train_random_erasing: true
      eval:
        ensure_rgb: true
        val_resize: true
        val_center_crop: true
    training:
      epochs: 5
      batch_size: 128
      num_workers: 8
      resume: auto
      lr: 0.0002
      weight_decay: 0.05

selection:
  # - efficientnet_b3
  # - efficientformerv2_s1
  # - faster_vit_2_224
  - repvit_m1